export const teams = [
  {
    id: "Actividades Subacuáticas Estudiantes ",
    name: "Actividades Subacuáticas Femenino y Masculino",
    schedule: "Lunes, Miércoles y Viernes de 4:15 PM a 6:00 PM",
    coach: "Brayan Andrés Valencia Aristizabal",
    location: "Piscina CDU (MELÉNDEZ)",
    email: "brayan.valencia.aristizabal@correounivalle.edu.co",
  },
  {
    id: "Actividades Subacuáticas Funcionarios ",
    name: "Actividades Subacuáticas Femenino y Masculino",
    schedule: "Martes, Miércoles, Jueves y Viernes de 5:00 PM a 7:00 PM",
    coach: "NO ASIGNADO",
    location: "Piscina CDU (MELÉNDEZ)",
    email: "...",
  },
  {
    id: "Ajedrez Estudiantes y Funcionarios",
    name: "Ajedrez Femenino/Masculino Estudiantes y Funcionarios",
    schedule: "Lunes de 11:00AM a 1:00PM , Miércoles de 10:00AM a 12:00PM y Viernes de 8:00 AM a 12:00 PM",
    coach: "Fabián Restrepo Santa",
    location: "Lunes es Virtual, Miércoles y Viernes en el Salón de Ajedrez",
    email: "entrenador.ajedrez@correounivalle.edu.co",
  },
  {
    id: "Atletismo Estudiantes y Funcionarios",
    name: "Atletismo Femenino y Masculino Estudiantes",
    schedule: "Lunes, Miercoles y Viernes de 2:00 PM a 4:00 PM, Martes, Jueves y Viernes de 5:30 PM a 7:30Pm Miércoles y Viernes de 6:30 AM a 8:30 AM",
    coach: "José Arturo Posada Noreña",
    location: "Pista de Trote Cancha #1 Melendez, El equipo representativo entrenan en la liga de Atletismo estadio Pedro Grajales de Lunes a viernes de 4:30PM a 8:00 PM",
    email: "saltoconpertiga@hotmail.com",
  },
  {
    id: "Balonmano Semillero ",
    name: "Balonmano Semillero Masculino/Femenino",
    schedule: "Lunes y Miércoles de 6:00 PM a 8:00 PM",
    coach: "NO ASIGNADO",
    location: "Canchas Exteriores",
    email: "...",
  },
  {
    id: "Baloncesto Estudiantes",
    name: "Baloncesto Estudiantes Masculino y Femenino",
    schedule: "Lunes y Viernes de 10:00 AM a 12:00 PM, Miercoles y Jueves de 4:00 PM a 6:00 PM",
    coach: "James Valdés Caicedo",
    location: "Lunes, Jueves y Viernes en el Coliseo, Miércoles en la Cancha Exterior Meléndez",
    email: "valdesjames@gmail.com",
  },
  {
    id: "Baloncesto Semillero Estudiantes ",
    name: "Baloncesto Semillero Masculino/Femenino ",
    schedule: "Jueves y Viernes de 4:00 PM a 6:00 PM",
    coach: "Cesar Danir Vergara Torres",
    location: "Cancha Exterior Meléndez",
    email: "cesar.vergara@correounivalle.edu.co",
  },
  {
    id: "Baloncesto Funcionarios ",
    name: "Baloncesto Funcionarios Masculino/Femenino ",
    schedule: "Lunes y Viernes de 12:00 PM a 2:00 PM, Jueves de 4:00 PM a 6:00 PM",
    coach: "James Valdés Caicedo",
    location: "Luens y Viernes en el Coliseo, Jueves en la Cancha Exterior Meléndez",
    email: "valdesjames@gmail.com",
  },
  {
    id: "Fútbol Sala Femenino Estudiantes	",
    name: "Fútbol Sala Femenino Estudiantes	",
    schedule: "Lunes y Miércoles de 2:00 PM a 4:00 PM, Viernes de 5:00 PM a 7:00 PM",
    coach: "NO ASIGNADO",
    location: " Miercoles y Viernes en el coliseo, Lunes en la Cancha Exterior Meléndez",
    email: "...",
  },
  {
    id: "Fútbol Sala Femenino Funcionarias",
    name: "Fútbol Sala Femenino Funcionarias",
    schedule: "Lunes y Miércoles de 2:00 PM a 4:00 PM, Viernes de 5:00 PM a 7:00 PM",
    coach: "NO ASIGNADO",
    location: " Miercoles y Viernes en el coliseo, Lunes en la Cancha Exterior Meléndez",
    email: "...",
  },
  {
    id: "Fútbol Sala Masculino Estudiantes",
    name: "Fútbol Sala Masculino Estudiantes",
    schedule: "Lunes de 6:00 PM a 8:00 PM, Martes y Jueves de 12:00 PM a 2:00 PM",
    coach: "Luis Ernesto Mora Olarte",
    location: "Coliseo (Meléndez)",
    email: "luisaomora87@hotmail.com",
  },
  {
    id: "Fútbol Sala Masculino Funcionarios",
    name: "Fútbol Sala Masculino Funcionarios",
    schedule: "Lunes de 2:00 PM a 4:00 PM, Viernes de 3:00 PM a 5:00 PM",
    coach: "Luis Ernesto Mora Olarte",
    location: "Coliseo (Meléndez)",
    email: "luisaomora87@hotmail.com",
  },
  {
    id: "Fútbol Femenino Estudiantes",
    name: "Fútbol Femenino Estudiantes",
    schedule: "lunes, miércoles y viernes de 12:00 PM a 2:00 PM",
    coach: "Milton Fabián Torres Córdoba",
    location: "Cancha #3, Meléndez",
    email: "milfatoc@gmail.com",
  },
  {
    id: "Fútbol Masculino Estudiantes",
    name: "Fútbol Masculino Estudiantes",
    schedule: "Lunes, Martes, Miércoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "Mauricio Ortiz García",
    location: "Cancha #2, Meléndez",
    email: "wallyortiz@hotmail.com",
  },
  {
    id: "Fútbol Docentes",
    name: "Fútbol Docentes",
    schedule: "Martes, Jueves y Sabado de 4:00 PM a 6:00 PM",
    coach: "Edgar Hernán Hurtado Giraldo",
    location: "Cancha #3, Meléndez",
    email: "nanhurtado14@hotmail.com",
  },
  {
    id: "Fútbol Funcionarios",
    name: "Fútbol Funcionarios",
    schedule: "Martes, Jueves y Sabado de 4:00 PM a 6:00 PM",
    coach: "José Ariel Caicedo Balanta",
    location: "Cancha #2, Meléndez",
    email: "joseariel07@hotmail.com",
  },
  {
    id: "Judo Estudiantes",
    name: "Judo Estudiantes Masculino Y Femenino ",
    schedule: "Lunes, Miercoles y Viernes de 12:00 PM a 2:00 PM, sábados de 2:00 PM a 4:00 PM",
    coach: "Jonathan Armando Cuarán Ortiz",
    location: "Lunes y viernes (Interior Coliseo), Miércoles (Exterior Coliseo-Mural de Judo), Sábados (San Fernando)",
    email: "jonathanarman_623@hotmail.com",
  },
  {
    id: "Karate-Do Mixto Estudiantes",
    name: "Karate-Do Mixto Estudiantes",
    schedule: "Lunes, Martes, Jueves y Viernes de 12:00 PM a 2:00 PM",
    coach: "Gerardo David Gonzáles Estrada",
    location: "Lunes, Jueves y Viernes Coliseo - Parte Exterior (Meléndez), Martes y Viernes Salones KarateDo (San Fernando)",
    email: "gonzalezbiologia@gmail.com",
  },
  {
    id: "Muay Thai - Sanda Estudiantes",
    name: "Muay Thai - Sanda Estudiantes Masculino Y Femenino ",
    schedule: "Lunes, Martes, Miércoles, Jueves y Viernes de 12:00 PM a 2:00 PM",
    coach: "Jairo Andrés Velasquez  Bolivar",
    location: "Lunes, Miercoles y Viernes Coliseo parte exterior (Meléndez), Martes y Jueves salón del Dojo (San Fernando)",
    email: "jairo.velasquez@correounivalle.edu.co",
  },
  {
    id: "Natación Semillero	",
    name: "Natación Mixtp Semillero ",
    schedule: "Jueves de 12:00 a 2:00 PM",
    coach: "NO ASIGNADO",
    location: "Piscina, CDU (Meléndez, Univalle)",
    email: "...",
  },
  {
    id: "Natación Mixto Estudiantes",
    name: "Natación Mixto Estudiantes",
    schedule: "Lunes, Miércoles y Viernes de 12:00 PM a 2:00 PM, Martes y Jueves de 6:00 PM a 8:00 PM",
    coach: "NO ASIGNADO",
    location: "Piscina, CDU (Meléndez, Univalle)",
    email: "...",
  },
  // {
  //   id: "",
  //   name: "",
  //   schedule: "",
  //   coach: "",
  //   location: "",
  //   email: "",
  // },
  {
    id: "Aerorumba Funcionarios",
    name: "Aerorumba Funcionarios",
    schedule: "Lunes, Miércoles y Viernes de 6:30 PM a 8:00 PM",
    coach: "Walter Ordóñez Ortiz",
    location: "Coliseo (Exterior)",
    email: "waloo.o.o@hotmail.com",
  },
  {
    id: "Aerorumba Jubilados",
    name: "Aerorumba Jubilados",
    schedule: "Martes y Viernes de 8:00 PM a 9:00 PM",
    coach: "Walter Ordóñez Ortiz",
    location: "Coliseo (Exterior)",
    email: "waloo.o.o@hotmail.com",
  },
  
]

