export const teams = [
  {
    id: "Actividades Subacuáticas Estudiantes ",
    name: "Actividades Subacuáticas Femenino y Masculino",
    schedule: "Lunes, Miércoles y Viernes de 4:15 PM a 6:00 PM",
    coach: "Brayan Andrés Valencia Aristizabal",
    location: "Piscina CDU (MELÉNDEZ)",
    email: "brayan.valencia.aristizabal@correounivalle.edu.co",
  },

  {
    id: "Ajedrez Estudiantes y Funcionarios",
    name: "Ajedrez Femenino/Masculino Estudiantes y Funcionarios",
    schedule: "Lunes de 11:00AM a 1:00PM , Miércoles de 10:00AM a 12:00PM y Viernes de 8:00 AM a 12:00 PM",
    coach: "Fabián Restrepo Santa",
    location: "Lunes es Virtual, Miércoles y Viernes en el Salón de Ajedrez",
    email: "entrenador.ajedrez@correounivalle.edu.co",
  },
  {
    id: "Atletismo Masculino y Femenino Estudiantes y Funcionarios",
    name: "Atletismo Masculino y Femenino Estudiantes y Funcionarios ",
    schedule: "Lunes, Miércoles y Viernes de 12:00 a 14:00. Martes, Jueves y Viernes de 17:30 a 19:30",
    coach: "José Arturo Posada Noreña",
    location: "Pista de Trote",
    email: "saltoconpertiga@hotmail.com",
  },
  {
    id: "Balonmano semillero Masculino y Femenino",
    name: "Balonmano semillero Masculino y Femenino ",
    schedule: "Lunes de 8:00 a 10:00 AM. Miércoles de 18:00 a 20:00 PM",
    coach: "Carlos Arturo Ramos Rosero",
    location: "Canchas exteriores",
    email: "carlos.arturo.ramos@correounivalle.edu.co",
  },
  {
    id: "Baloncesto Estudiantes",
    name: "Baloncesto Estudiantes Masculino y Femenino",
    schedule: "Lunes y Viernes de 10:00 AM a 12:00 PM, Miercoles y Jueves de 4:00 PM a 6:00 PM",
    coach: "James Valdés Caicedo",
    location: "Lunes, Jueves y Viernes en el Coliseo, Miércoles en la Cancha Exterior Meléndez",
    email: "valdesjames@gmail.com",
  },
  {
    id: "Baloncesto Semillero Estudiantes ",
    name: "Baloncesto Semillero Masculino/Femenino ",
    schedule: "Jueves y Viernes de 4:00 PM a 6:00 PM",
    coach: "Cesar Danir Vergara Torres",
    location: "Cancha Exterior Meléndez",
    email: "cesar.vergara@correounivalle.edu.co",
  },
  {
    id: "Baloncesto Funcionarios ",
    name: "Baloncesto Funcionarios Masculino/Femenino ",
    schedule: "Lunes y Viernes de 12:00 PM a 2:00 PM, Jueves de 4:00 PM a 6:00 PM",
    coach: "James Valdés Caicedo",
    location: "Luens y Viernes en el Coliseo, Jueves en la Cancha Exterior Meléndez",
    email: "valdesjames@gmail.com",
  },
  {
    id: "Fútbol Sala Femenino Estudiantes/Funcionarias",
    name: "Fútbol Sala Femenino Estudiantes/Funcionarias",
    schedule: "Lunes de 16:00 a 18:00, Martes y Miércoles de 12:00 a 14:00 y Viernes de 17:00 a 19:00",
    coach: "Froilan Esteban López Yatacué",
    location: "Lunes y Martes: Canchas exteriores, Miércoles y Viernes: Coliseo Meléndez",
    email: "froilan.lopez@correounivalle.edu.co",
  },
  {
    id: "Fútbol Sala Masculino Estudiantes",
    name: "Fútbol Sala Masculino Estudiantes",
    schedule: "Lunes de 6:00 PM a 8:00 PM, Martes y Jueves de 12:00 PM a 2:00 PM",
    coach: "Luis Ernesto Mora Olarte",
    location: "Coliseo (Meléndez)",
    email: "luisaomora87@hotmail.com",
  },
  {
    id: "Fútbol Sala Masculino Funcionarios",
    name: "Fútbol Sala Masculino Funcionarios",
    schedule: "Lunes de 2:00 PM a 4:00 PM, Viernes de 3:00 PM a 5:00 PM",
    coach: "Luis Ernesto Mora Olarte",
    location: "Coliseo (Meléndez)",
    email: "luisaomora87@hotmail.com",
  },
  {
    id: "Fútbol Femenino Estudiantes",
    name: "Fútbol Femenino Estudiantes",
    schedule: "lunes, miércoles y viernes de 12:00 PM a 2:00 PM",
    coach: "Milton Fabián Torres Córdoba",
    location: "Cancha #3, Meléndez",
    email: "milfatoc@gmail.com",
  },
  {
    id: "Fútbol Masculino Estudiantes",
    name: "Fútbol Masculino Estudiantes",
    schedule: "Lunes, Martes, Miércoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "Mauricio Ortiz García",
    location: "Cancha #2, Meléndez",
    email: "wallyortiz@hotmail.com",
  },
  {
    id: "Fútbol Docentes",
    name: "Fútbol Docentes",
    schedule: "Martes, Jueves y Sabado de 4:00 PM a 6:00 PM",
    coach: "Edgar Hernán Hurtado Giraldo",
    location: "Cancha #3, Meléndez",
    email: "nanhurtado14@hotmail.com",
  },
  {
    id: "Fútbol Funcionarios",
    name: "Fútbol Funcionarios",
    schedule: "Martes, Jueves y Sabado de 4:00 PM a 6:00 PM",
    coach: "José Ariel Caicedo Balanta",
    location: "Cancha #2, Meléndez",
    email: "joseariel07@hotmail.com",
  },
  {
    id: "Judo Estudiantes",
    name: "Judo Estudiantes Masculino Y Femenino ",
    schedule: "Lunes, Miercoles y Viernes de 12:00 PM a 2:00 PM, sábados de 2:00 PM a 4:00 PM",
    coach: "Jonathan Armando Cuarán Ortiz",
    location: "Lunes y viernes (Interior Coliseo), Miércoles (Exterior Coliseo-Mural de Judo), Sábados (San Fernando)",
    email: "jonathanarman_623@hotmail.com",
  },
  {
    id: "Karate-Do Mixto Estudiantes",
    name: "Karate-Do Mixto Estudiantes",
    schedule: "Lunes, Martes, Jueves y Viernes de 12:00 PM a 2:00 PM",
    coach: "Gerardo David Gonzáles Estrada",
    location: "Lunes, Jueves y Viernes Coliseo - Parte Exterior (Meléndez), Martes y Viernes Salones KarateDo (San Fernando)",
    email: "gonzalezbiologia@gmail.com",
  },
  {
    id: "Muay Thai - Sanda Estudiantes",
    name: "Muay Thai - Sanda Estudiantes Masculino Y Femenino ",
    schedule: "Lunes, Martes, Miércoles, Jueves y Viernes de 12:00 PM a 2:00 PM",
    coach: "Jairo Andrés Velasquez  Bolivar",
    location: "Lunes, Miercoles y Viernes Coliseo parte exterior (Meléndez), Martes y Jueves salón del Dojo (San Fernando)",
    email: "jairo.velasquez@correounivalle.edu.co",
  },
  {
    id: "Natación Semilleros",
    name: "Natación Semilleros",
    schedule: "Miércoles y Jueves de 18:00 a 20:00 PM",
    coach: "Monitor: Jose David Prieto",
    location: "Piscina CDU Meléndez",
    email: "",
  },
  {
    id: "Natación Estudiantes Masculino y Femenino",
    name: "Natación Estudiantes Masculino y Femenino",
    schedule: "Lunes y Viernes de 12:00 a 14:00 PM",
    coach: "NO ASIGNADO",
    location: "Piscina CDU Meléndez",
    email: "...",
  },
  {
    id: "Patinaje Mixto Estudiantes",
    name: "Patinaje Mixto Estudiantes",
    schedule: "Lunes y Miercoles de 5:00 PM a 8:30PM, Viernes de 5:00PM a 7:00PM",
    coach: "Julieth Candamil Ríos",
    location: "Canchas Exteriores (Melendez, Univalle) y Liga Vallecaucana de Patinaje(Patinodoromo Mundialista)",
    email: "julieth.candamil@correounivalle.edu.co",
  },
  {
    id: "Patinaje Semillero  Masculino/Femenino ",
    name: "Patinaje Semillero  Masculino/Femenino ",
    schedule: "Martes y Jueves de 7:00 PM a 8:30 PM",
    coach: "NO ASIGNADO",
    location: "Canchas auxiliares de baloncesto ",
    email: "NO ASIGNADO",
  },
  {
    id: "Porrismo Mixto Estudiantes",
    name: "Porrismo Mixto Estudiantes",
    schedule: "Lunes Miercoles y Viernes de 12:00PM a 2:00PM",
    coach: "Jairo Andrés Espinosa Silva ",
    location: "Coliseo (Exterior)",
    email: "jairo.espinosa@correounivalle.edu.co",
  },
  {
    id: "Polo Acúatico Masculino",
    name: "Polo Acúatico Masculino",
    schedule: "Lunes Martes Miercoles y Jueves de 12:00PM a 2:00PM",
    coach: "NO ASIGNADO",
    location: "Piscina, CDU (Meléndez, Univalle)",
    email: "NO ASIGNADO",
  },
  {
    id: "Polo Acúatico Femenino",
    name: "Polo Acúatico Femenino",
    schedule: "Lunes Martes Jueves y Viernes de 12:00PM a 2:00PM",
    coach: "NO ASIGNADO",
    location: "Piscina, CDU (Meléndez, Univalle)",
    email: "NO ASIGNADO",
  },
  {
    id: "Rugby Femenino Estudiantes",
    name: "Rugby Femenino Estudiantes",
    schedule: "Lunes, Miércoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "José Felipe Sanclemente Alixandre	",
    location: "Cancha N°7 - Meléndez, Univalle	",
    email: "felipejfsa@gmail.com",
  },
  {
    id: "Rugby Femenino Principiantes",
    name: "Rugby Femenino Principiantes",
    schedule: "Lunes, Miércoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "José Felipe Sanclemente Alixandre	",
    location: "Cancha N°7 - Meléndez, Univalle",
    email: "felipejfsa@gmail.com",
  },
  {
    id: "Rugby Masculino Estudiantes",
    name: "Rugby Masculino Estudiantes",
    schedule: "Lunes, Miércoles y Viernes de 12:00 a 14:00. Martes y Jueves de 12:00 a 14:00",
    coach: "Efraín Paz García",
    location: "Lunes, Miércoles y Viernes: Cancha N°7-Meléndez, Univalle Martes y Jueves: Afueras del Coliseo Meléndez",
    email: "fliachupaz@gmail.com",
  },
  {
    id: "Rugby Masculino Principiantes",
    name: "Rugby Masculino Principiantes",
    schedule: "Lunes, Miércoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "Efraín Paz García	",
    location: "Cancha N°7 - Meléndez, Univalle",
    email: "fliachaupaz@gmail.com",
  },
  {
    id: "Taekwondo mixto",
    name: "Taekwondo Mixto ",
    schedule: "Lunes de 12:00 a 14:00, Martes de 10:00 a 12:00, Miércoles de 13:00 a 15:00 y Jueves de 11:00 a 13:00",
    coach: "Johann Alexander Serrano Hoyos",
    location: "Afueras del Coliseo",
    email: "johann.serrano@correounivalle.edu.co",
  },
  {
    id: "Tenis de Campo Avanzado Mixto Estudiantes",
    name: "Tenis de Campo Avanzado Mixto Estudiantes",
    schedule: "Lunes, Miercoles y Viernes de 12:00 PM a 2:00 PM",
    coach: "NO ASIGNADO",
    location: "Cancha de Tenis de Campo, CDU (Meléndez, Univalle)",
    email: "NO ASIGNADO",
  },
  {
    id: "Tenis de Campo Principiantes Mixto Estudiantes",
    name: "Tenis de Campo Principiantes Mixto Estudiantes",
    schedule: "Martes y Jueves de 4:00 PM a 6:00 PM",
    coach: "NO ASIGNADO",
    location: "Cancha de Tenis de Campo, CDU (Meléndez, Univalle)",
    email: "NO ASIGNADO",
  },
  {
    id: "Tenis de Campo Mixto Funcionarios",
    name: "Tenis de Campo Mixto Funcionarios",
    schedule: "Lunes y Viernes de 4:00 PM a 6:00 PM",
    coach: "NO ASIGNADO",
    location: "Cancha de Tenis de Campo, CDU (Meléndez, Univalle)",
    email: "NO ASIGNADO",
  },
  {
    id: "Tenis de Mesa Mixto Estudiantes",
    name: "Tenis de Mesa Mixto Estudiantes",
    schedule: "Lunes, Martes, Miércoles(SEMILLERO), Jueves y Viernes  de 12:00 PM a 2:00 PM",
    coach: "César Daniel Ibañez Páez",
    location: "Salón de Tenis de Mesa (Meléndez, Univalle)",
    email: "danielibanez.paez@gmail.com",
  },
  {
    id: "Tenis de Mesa Mixto Funcionarios	",
    name: "Tenis de Mesa Mixto Funcionarios	",
    schedule: "Miercoles y Viernes de 3:00PM a 5:00PM",
    ccoach: "César Daniel Ibañez Páez",
    location: "Salón de Tenis de Mesa (Meléndez, Univalle)",
    email: "danielibanez.paez@gmail.com",
  },
  {
    id: "Ultimate Mixto Estudiantes	",
    name: "Ultimate Mixto Estudiantes	",
    schedule: "Lunes, Miércoles y Viernes de 12:00 PM a 2:00 PM, Sabados de 12:00PM a 4:00PM",
    coach: "Hugo Alejandro Lasso Vélez",
    location: "Cancha N°4 - Meléndez, Univalle	",
    email: "hugo.lasso@correounivalle.edu.co",
  },
  {
    id: "Ultimate Mixto Principiantes	",
    name: "Ultimate Mixto Principiantes	",
    schedule: "Martes y Jueves de 12:00 PM a 2:00 PM",
    coach: "Hugo Alejandro Lasso Vélez",
    location: "Cancha N°4 - Meléndez, Univalle	",
    email: "hugo.lasso@correounivalle.edu.co",
  },
  {
    id: "Voleibol Arena - Selección",
    name: "Voleibol Arena - Selección",
    schedule: "Lunes y Miercoles de 10:00 AM a 12:00 PM, Y Viernes de 8:00AM a 10:00AM",
    coach: "Martha Cecilia Medina Aedo	",
    location: "Lunes Y Viernes Cancha Voleibol Arena CDU (Meléndez, Univalle), Miercoles y Sabado Cancha Barena 	",
    email: "marthacmedinaaedo@gmail.com",
  },
  {
    id: "Voleibol Arena Estudiantes Femenino ",
    name: "Voleibol Arena Estudiantes Femenino ",
    schedule: "Lunes y Miercoles de 10:00 AM a 12:00 PM",
    coach: "Martha Cecilia Medina Aedo	",
    location: "Cancha Voleibol Arena, CDU (Meléndez, Univalle)",
    email: "marthacmedinaaedo@gmail.com",
  },
  {
    id: "Voleibol Arena Estudiantes Masculino ",
    name: "Voleibol Arena Estudiantes Masculino ",
    schedule: "Lunes y Miercoles de 10:00 AM a 12:00 PM",
    coach: "Martha Cecilia Medina Aedo	",
    location: "Cancha Voleibol Arena, CDU (Meléndez, Univalle)",
    email: "marthacmedinaaedo@gmail.com",
  },
  {
    id: "Voleibol Avanzado Mixto Estudiantes",
    name: "Voleibol Avanzado Mixto Estudiantes",
    schedule: "Martes de 5:30 PM a 8:00PM, Miercoles y Viernes de 6:30 PM a 9:00 PM",
    coach: "Juan Sebastián Salazar ",
    location: "Coliseo (Meléndez, Univalle)",
    email: "juans3b4s@gmail.com",
  },
  {
    id: "Semillero Voleibol Mixto Estudiantes",
    name: "Semillero Voleibol Mixto Estudiantes",
    schedule: "Lunes de 6:00 PM a 8:00 PM",
    coach: "Juan Sebastián Salazar",
    location: "Canchas Exteriores (Meléndez, Univalle)",
    email: "juans3b4s@gmail.com",
  },
  {
    id: "Voleibol Femenino Sintraunicol",
    name: "Voleibol Femenino Sintraunicol",
    schedule: "Lunes y Miércoles de 17:00 a 19:00 Viernes de 6:30 a 8:30",
    coach: "Divier Palacios Saenz",
    location: "Coliseo Sede Meléndez",
    email: "divier2049@gmail.com",
  },
  {
    id: "Voleibol Femenino Funcionarias",
    name: "Voleibol Femenino Funcionarias",
    schedule: "Martes y Jueves de 6:30 AM a 8:00 AM, Sábados de 12:00 PM a 2:00 PM",
    coach: "Bellanira Rengifo",
    location: "Coliseo (Meléndez, Univalle)",
    email: "beyaren@hotmail.com",
  },
  {
    id: "Voleibol Masculino Funcionarios",
    name: "Voleibol Masculino Funcionarios",
    schedule: "Lunes Jueves y Sábado de 4:00 PM a 6:00 PM",
    coach: "Luis Natalio Lozano Camacho",
    location: "Coliseo (Meléndez, Univalle)",
    email: "lunaloca80@yahoo.com",
  },
  // {
  //   id: "",
  //   name: "",
  //   schedule: "",
  //   coach: "",
  //   location: "",
  //   email: "",
  // },
  // {
  //   id: "",
  //   name: "",
  //   schedule: "",
  //   coach: "",
  //   location: "",
  //   email: "",
  // },
  {
    id: "Aerorumba Funcionarios",
    name: "Aerorumba Funcionarios",
    schedule: "Lunes, Miércoles y Viernes de 6:30 PM a 8:00 PM",
    coach: "Walter Ordóñez Ortiz",
    location: "Coliseo (Exterior)",
    email: "waloo.o.o@hotmail.com",
  },
  {
    id: "Aerorumba Jubilados",
    name: "Aerorumba Jubilados",
    schedule: "Martes y Viernes de 8:00 PM a 9:00 PM",
    coach: "Walter Ordóñez Ortiz",
    location: "Coliseo (Exterior)",
    email: "waloo.o.o@hotmail.com",
  },
  
]

